### ISSUE TITLE
Support health check in Proxy

### ISSUE THREAD

**Issue by appleboy** [appleboy/loadbalancer-algorithms#12]
```yaml
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    args:
    - liveness
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
```
